export const TOAST_STRING_DURATION_MS = 2800;
export const TOAST_DEFAULT_DURATION_MS = 3600;
export const TOAST_ACTION_DURATION_MS = 6200;
export const EXPORT_TRANSIENT_FEEDBACK_MS = 2200;
export const PREVIEW_SOURCE_FLASH_MS = 1800;
