import type { CommandContext, CommandDefinition, CommandId } from '../types';

interface EditorCommandDeps {
  hasDocument: (context: CommandContext) => boolean;
  emitEditorCommand: (command: string, detail?: Record<string, unknown>) => void;
  emitInlineFormat: (format: string) => void;
  emitBlockFormat: (format: string) => void;
  emitHeading: (level: string) => void;
}

export function createEditorCommands(deps: EditorCommandDeps): CommandDefinition[] {
  const {
    hasDocument,
    emitEditorCommand,
    emitInlineFormat,
    emitBlockFormat,
    emitHeading,
  } = deps;

  return [
    {
      id: 'undo',
      label: '撤销',
      category: '编辑',
      keywords: ['undo'],
      shortcuts: [{ code: 'KeyZ', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('undo'),
    },
    {
      id: 'redo',
      label: '重做',
      category: '编辑',
      keywords: ['redo'],
      shortcuts: [
        { code: 'KeyZ', mod: true, shift: true },
        { code: 'KeyY', mod: true, platforms: ['windows', 'linux'] },
      ],
      enabled: hasDocument,
      run: () => emitEditorCommand('redo'),
    },
    {
      id: 'cut',
      label: '剪切',
      category: '编辑',
      keywords: ['cut'],
      shortcuts: [{ code: 'KeyX', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('cut'),
    },
    {
      id: 'copy',
      label: '复制',
      category: '编辑',
      keywords: ['copy'],
      shortcuts: [{ code: 'KeyC', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('copy'),
    },
    {
      id: 'paste',
      label: '粘贴',
      category: '编辑',
      keywords: ['paste'],
      shortcuts: [{ code: 'KeyV', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('paste'),
    },
    {
      id: 'pastePlain',
      label: '粘贴并匹配样式',
      category: '编辑',
      shortcuts: [{ code: 'KeyV', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('pastePlain'),
    },
    {
      id: 'selectAll',
      label: '全选',
      category: '编辑',
      shortcuts: [{ code: 'KeyA', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectAll'),
    },
    {
      id: 'showSearch',
      label: '查找',
      category: '编辑',
      keywords: ['find', 'search'],
      shortcuts: [{ code: 'KeyF', mod: true }],
      enabled: hasDocument,
      run: () => {
        window.dispatchEvent(new CustomEvent('prism-search', { detail: { action: 'open' } }));
      },
    },
    {
      id: 'workspaceSearch',
      label: '全文搜索工作区',
      category: '编辑',
      keywords: ['search', 'workspace', 'full text', '全文', '工作区'],
      shortcuts: [{ code: 'KeyF', mod: true, shift: true }],
      enabled: (context) => Boolean(context.workspaceStore.rootPath && context.workspaceStore.fileTree.length > 0),
      run: (context) => context.openWorkspaceSearch?.(),
    },
    {
      id: 'showReplace',
      label: '替换',
      category: '编辑',
      keywords: ['replace', 'find'],
      shortcuts: [{ code: 'KeyH', mod: true }],
      enabled: hasDocument,
      run: () => {
        window.dispatchEvent(new CustomEvent('prism-search', { detail: { action: 'replace' } }));
      },
    },
    {
      id: 'copyPlain',
      label: '复制为纯文本',
      category: '编辑',
      enabled: hasDocument,
      run: () => emitEditorCommand('copyPlain'),
    },
    {
      id: 'copyMd',
      label: '复制为 Markdown',
      category: '编辑',
      shortcuts: [{ code: 'KeyC', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyMd'),
    },
    {
      id: 'copyHtml',
      label: '复制为 HTML',
      category: '编辑',
      enabled: hasDocument,
      run: () => emitEditorCommand('copyHtml'),
    },
    {
      id: 'link',
      label: '链接',
      category: '插入',
      keywords: ['link'],
      shortcuts: [{ code: 'KeyK', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('link'),
    },
    {
      id: 'codeBlock',
      label: '代码块',
      category: '插入',
      keywords: ['code', 'block'],
      shortcuts: [{ code: 'KeyK', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('codeBlock'),
    },
    {
      id: 'mathBlock',
      label: '公式块',
      category: '插入',
      shortcuts: [{ code: 'KeyM', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('mathBlock'),
    },
    {
      id: 'quote',
      label: '引用',
      category: '插入',
      shortcuts: [{ code: 'KeyQ', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('quote'),
    },
    {
      id: 'orderedList',
      label: '有序列表',
      category: '插入',
      shortcuts: [{ code: 'BracketLeft', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('orderedList'),
    },
    {
      id: 'unorderedList',
      label: '无序列表',
      category: '插入',
      shortcuts: [{ code: 'BracketRight', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('unorderedList'),
    },
    {
      id: 'taskList',
      label: '任务列表',
      category: '插入',
      shortcuts: [{ code: 'KeyX', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('taskList'),
    },
    {
      id: 'insertTable',
      label: '插入表格',
      category: '插入',
      keywords: ['table'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTable'),
    },
    {
      id: 'formatTable',
      label: '格式化当前表格',
      category: '插入',
      keywords: ['table', 'format'],
      enabled: hasDocument,
      run: () => emitEditorCommand('formatTable'),
    },
    {
      id: 'addTableRow',
      label: '添加表格行',
      category: '插入',
      keywords: ['table', 'row'],
      enabled: hasDocument,
      run: () => emitEditorCommand('addTableRow'),
    },
    {
      id: 'addTableColumn',
      label: '添加表格列',
      category: '插入',
      keywords: ['table', 'column'],
      enabled: hasDocument,
      run: () => emitEditorCommand('addTableColumn'),
    },
    {
      id: 'deleteTableRow',
      label: '删除表格行',
      category: '插入',
      keywords: ['table', 'row', 'delete'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteTableRow'),
    },
    {
      id: 'deleteTableColumn',
      label: '删除表格列',
      category: '插入',
      keywords: ['table', 'column', 'delete'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteTableColumn'),
    },
    {
      id: 'hr',
      label: '水平分割线',
      category: '插入',
      enabled: hasDocument,
      run: () => emitBlockFormat('hr'),
    },
    {
      id: 'footnote',
      label: '脚注',
      category: '插入',
      enabled: hasDocument,
      run: () => emitBlockFormat('footnote'),
    },
    {
      id: 'linkReference',
      label: '链接引用',
      category: '插入',
      enabled: hasDocument,
      run: () => emitBlockFormat('linkReference'),
    },
    {
      id: 'toc',
      label: '内容目录',
      category: '插入',
      enabled: hasDocument,
      run: () => emitBlockFormat('toc'),
    },
    {
      id: 'yaml',
      label: 'YAML Front Matter',
      category: '插入',
      enabled: hasDocument,
      run: () => emitBlockFormat('yaml'),
    },
    {
      id: 'bold',
      label: '粗体',
      category: '格式',
      keywords: ['bold'],
      shortcuts: [{ code: 'KeyB', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('bold'),
    },
    {
      id: 'italic',
      label: '斜体',
      category: '格式',
      keywords: ['italic'],
      shortcuts: [{ code: 'KeyI', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('italic'),
    },
    {
      id: 'underline',
      label: '下划线',
      category: '格式',
      keywords: ['underline'],
      shortcuts: [{ code: 'KeyU', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('underline'),
    },
    {
      id: 'strikethrough',
      label: '删除线',
      category: '格式',
      keywords: ['strikethrough'],
      shortcuts: [{ code: 'Digit5', alt: true, shift: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('strikethrough'),
    },
    {
      id: 'inlineCode',
      label: '行内代码',
      category: '格式',
      keywords: ['code'],
      shortcuts: [{ code: 'Backquote', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('code'),
    },
    {
      id: 'paragraph',
      label: '正文',
      category: '格式',
      keywords: ['paragraph'],
      shortcuts: [{ code: 'Digit0', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('paragraph'),
    },
    ...([1, 2, 3, 4, 5, 6] as const).map((level) => ({
      id: `h${level}` as CommandId,
      label: `${['一', '二', '三', '四', '五', '六'][level - 1]}级标题`,
      category: '格式' as const,
      keywords: [`h${level}`, 'heading'],
      shortcuts: [{ code: `Digit${level}`, mod: true }],
      enabled: hasDocument,
      run: () => emitHeading(`h${level}`),
    })),
    {
      id: 'increaseHeading',
      label: '提升标题级别',
      category: '格式',
      shortcuts: [{ code: 'Equal', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('increaseHeading'),
    },
    {
      id: 'decreaseHeading',
      label: '降低标题级别',
      category: '格式',
      shortcuts: [{ code: 'Minus', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('decreaseHeading'),
    },
    {
      id: 'clearFormat',
      label: '清除格式',
      category: '格式',
      shortcuts: [{ code: 'Backslash', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('clearFormat'),
    },
    {
      id: 'moveParagraphUp',
      label: '段落上移',
      category: '格式',
      keywords: ['block', 'paragraph', 'move', 'up'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveParagraphUp'),
    },
    {
      id: 'moveParagraphDown',
      label: '段落下移',
      category: '格式',
      keywords: ['block', 'paragraph', 'move', 'down'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveParagraphDown'),
    },
    {
      id: 'duplicateParagraph',
      label: '复制当前段落',
      category: '格式',
      keywords: ['block', 'paragraph', 'duplicate', 'copy'],
      enabled: hasDocument,
      run: () => emitEditorCommand('duplicateParagraph'),
    },
    {
      id: 'deleteParagraph',
      label: '删除当前段落',
      category: '格式',
      keywords: ['block', 'paragraph', 'delete', 'remove'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteParagraph'),
    },
    {
      id: 'moveSectionUp',
      label: '章节上移',
      category: '格式',
      keywords: ['block', 'section', 'heading', 'move', 'up'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveSectionUp'),
    },
    {
      id: 'moveSectionDown',
      label: '章节下移',
      category: '格式',
      keywords: ['block', 'section', 'heading', 'move', 'down'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveSectionDown'),
    },
    {
      id: 'duplicateSection',
      label: '复制当前章节',
      category: '格式',
      keywords: ['block', 'section', 'heading', 'duplicate', 'copy'],
      enabled: hasDocument,
      run: () => emitEditorCommand('duplicateSection'),
    },
    {
      id: 'foldCurrentHeading',
      label: '折叠当前标题',
      category: '格式',
      keywords: ['block', 'section', 'heading', 'fold'],
      enabled: hasDocument,
      run: () => emitEditorCommand('foldCurrentHeading'),
    },
    {
      id: 'selectionQuote',
      label: '选区转引用',
      category: '格式',
      keywords: ['block', 'selection', 'quote'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionQuote'),
    },
    {
      id: 'selectionCalloutNote',
      label: '选区转 Note Callout',
      category: '格式',
      keywords: ['block', 'selection', 'callout', 'note'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutNote'),
    },
    {
      id: 'selectionCalloutWarning',
      label: '选区转 Warning Callout',
      category: '格式',
      keywords: ['block', 'selection', 'callout', 'warning'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutWarning'),
    },
    {
      id: 'selectionCalloutTip',
      label: '选区转 Tip Callout',
      category: '格式',
      keywords: ['block', 'selection', 'callout', 'tip'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutTip'),
    },
    {
      id: 'selectionUnorderedList',
      label: '选区转无序列表',
      category: '格式',
      keywords: ['block', 'selection', 'list', 'unordered'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionUnorderedList'),
    },
    {
      id: 'selectionOrderedList',
      label: '选区转有序列表',
      category: '格式',
      keywords: ['block', 'selection', 'list', 'ordered'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionOrderedList'),
    },
    {
      id: 'selectionTaskList',
      label: '选区转任务列表',
      category: '格式',
      keywords: ['block', 'selection', 'task', 'list'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionTaskList'),
    },
  ] satisfies CommandDefinition[];
}
