import type { CommandContext, CommandDefinition, CommandId } from '../types';
import { emitAppEvent } from '../../../platform/events/appEvents';

interface EditorCommandDeps {
  hasDocument: (context: CommandContext) => boolean;
  emitEditorCommand: (command: string, detail?: Record<string, unknown>) => void;
  emitInlineFormat: (format: string) => void;
  emitBlockFormat: (format: string) => void;
  emitHeading: (level: string) => void;
}

export function createEditorCommands(deps: EditorCommandDeps): CommandDefinition[] {
  const {
    hasDocument,
    emitEditorCommand,
    emitInlineFormat,
    emitBlockFormat,
    emitHeading,
  } = deps;

  return [
    {
      id: 'undo',
      category: 'edit',
      keywords: ['undo'],
      shortcuts: [{ code: 'KeyZ', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('undo'),
    },
    {
      id: 'redo',
      category: 'edit',
      keywords: ['redo'],
      shortcuts: [
        { code: 'KeyZ', mod: true, shift: true },
        { code: 'KeyY', mod: true, platforms: ['windows', 'linux'] },
      ],
      enabled: hasDocument,
      run: () => emitEditorCommand('redo'),
    },
    {
      id: 'cut',
      category: 'edit',
      keywords: ['cut'],
      shortcuts: [{ code: 'KeyX', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('cut'),
    },
    {
      id: 'copy',
      category: 'edit',
      keywords: ['copy'],
      shortcuts: [{ code: 'KeyC', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('copy'),
    },
    {
      id: 'paste',
      category: 'edit',
      keywords: ['paste'],
      shortcuts: [{ code: 'KeyV', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('paste'),
    },
    {
      id: 'pastePlain',
      category: 'edit',
      shortcuts: [{ code: 'KeyV', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('pastePlain'),
    },
    {
      id: 'selectAll',
      category: 'edit',
      shortcuts: [{ code: 'KeyA', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectAll'),
    },
    {
      id: 'showSearch',
      category: 'edit',
      keywords: ['find', 'search'],
      shortcuts: [{ code: 'KeyF', mod: true }],
      enabled: hasDocument,
      run: () => {
        emitAppEvent('search.open', { action: 'open' });
      },
    },
    {
      id: 'workspaceSearch',
      category: 'edit',
      keywords: ['search', 'workspace', 'full text', '全文', '工作区'],
      shortcuts: [{ code: 'KeyF', mod: true, shift: true }],
      enabled: (context) => Boolean(context.workspaceStore.rootPath && context.workspaceStore.fileTree.length > 0),
      run: (context) => context.openWorkspaceSearch?.(),
    },
    {
      id: 'showReplace',
      category: 'edit',
      keywords: ['replace', 'find'],
      shortcuts: [{ code: 'KeyH', mod: true }],
      enabled: hasDocument,
      run: () => {
        emitAppEvent('search.open', { action: 'replace' });
      },
    },
    {
      id: 'copyPlain',
      category: 'edit',
      enabled: hasDocument,
      run: () => emitEditorCommand('copyPlain'),
    },
    {
      id: 'copyMd',
      category: 'edit',
      shortcuts: [{ code: 'KeyC', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyMd'),
    },
    {
      id: 'copyHtml',
      category: 'edit',
      enabled: hasDocument,
      run: () => emitEditorCommand('copyHtml'),
    },
    {
      id: 'link',
      category: 'insert',
      keywords: ['link'],
      shortcuts: [{ code: 'KeyK', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('link'),
    },
    {
      id: 'codeBlock',
      category: 'insert',
      keywords: ['code', 'block'],
      shortcuts: [{ code: 'KeyK', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('codeBlock'),
    },
    {
      id: 'mathBlock',
      category: 'insert',
      shortcuts: [{ code: 'KeyM', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('mathBlock'),
    },
    {
      id: 'quote',
      category: 'insert',
      shortcuts: [{ code: 'KeyQ', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('quote'),
    },
    {
      id: 'orderedList',
      category: 'insert',
      shortcuts: [{ code: 'BracketLeft', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('orderedList'),
    },
    {
      id: 'unorderedList',
      category: 'insert',
      shortcuts: [{ code: 'BracketRight', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('unorderedList'),
    },
    {
      id: 'taskList',
      category: 'insert',
      shortcuts: [{ code: 'KeyX', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('taskList'),
    },
    {
      id: 'insertTable',
      category: 'insert',
      keywords: ['table'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTable'),
    },
    {
      id: 'formatTable',
      category: 'insert',
      keywords: ['table', 'format'],
      enabled: hasDocument,
      run: () => emitEditorCommand('formatTable'),
    },
    {
      id: 'addTableRow',
      category: 'insert',
      keywords: ['table', 'row'],
      enabled: hasDocument,
      run: () => emitEditorCommand('addTableRow'),
    },
    {
      id: 'addTableColumn',
      category: 'insert',
      keywords: ['table', 'column'],
      enabled: hasDocument,
      run: () => emitEditorCommand('addTableColumn'),
    },
    {
      id: 'deleteTableRow',
      category: 'insert',
      keywords: ['table', 'row', 'delete'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteTableRow'),
    },
    {
      id: 'deleteTableColumn',
      category: 'insert',
      keywords: ['table', 'column', 'delete'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteTableColumn'),
    },
    {
      id: 'alignTableColumnLeft',
      category: 'insert',
      keywords: ['table', 'column', 'align', 'left'],
      enabled: hasDocument,
      run: () => emitEditorCommand('alignTableColumnLeft'),
    },
    {
      id: 'alignTableColumnCenter',
      category: 'insert',
      keywords: ['table', 'column', 'align', 'center'],
      enabled: hasDocument,
      run: () => emitEditorCommand('alignTableColumnCenter'),
    },
    {
      id: 'alignTableColumnRight',
      category: 'insert',
      keywords: ['table', 'column', 'align', 'right'],
      enabled: hasDocument,
      run: () => emitEditorCommand('alignTableColumnRight'),
    },
    {
      id: 'insertTableRowAbove',
      category: 'insert',
      keywords: ['table', 'row', 'above'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTableRowAbove'),
    },
    {
      id: 'insertTableRowBelow',
      category: 'insert',
      keywords: ['table', 'row', 'below'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTableRowBelow'),
    },
    {
      id: 'insertTableColumnLeft',
      category: 'insert',
      keywords: ['table', 'column', 'left'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTableColumnLeft'),
    },
    {
      id: 'insertTableColumnRight',
      category: 'insert',
      keywords: ['table', 'column', 'right'],
      enabled: hasDocument,
      run: () => emitEditorCommand('insertTableColumnRight'),
    },
    {
      id: 'moveTableRowUp',
      category: 'insert',
      keywords: ['table', 'row', 'move', 'up'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveTableRowUp'),
    },
    {
      id: 'moveTableRowDown',
      category: 'insert',
      keywords: ['table', 'row', 'move', 'down'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveTableRowDown'),
    },
    {
      id: 'moveTableColumnLeft',
      category: 'insert',
      keywords: ['table', 'column', 'move', 'left'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveTableColumnLeft'),
    },
    {
      id: 'moveTableColumnRight',
      category: 'insert',
      keywords: ['table', 'column', 'move', 'right'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveTableColumnRight'),
    },
    {
      id: 'selectTable',
      category: 'insert',
      keywords: ['table', 'select'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectTable'),
    },
    {
      id: 'copyTableMarkdown',
      category: 'insert',
      keywords: ['table', 'copy', 'markdown'],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyTableMarkdown'),
    },
    {
      id: 'copyTableHtml',
      category: 'insert',
      keywords: ['table', 'copy', 'html'],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyTableHtml'),
    },
    {
      id: 'copyTableCsv',
      category: 'insert',
      keywords: ['table', 'copy', 'csv'],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyTableCsv'),
    },
    {
      id: 'copyTableTsv',
      category: 'insert',
      keywords: ['table', 'copy', 'tsv'],
      enabled: hasDocument,
      run: () => emitEditorCommand('copyTableTsv'),
    },
    {
      id: 'sortTableAsc',
      category: 'insert',
      keywords: ['table', 'sort', 'ascending'],
      enabled: hasDocument,
      run: () => emitEditorCommand('sortTableAsc'),
    },
    {
      id: 'sortTableDesc',
      category: 'insert',
      keywords: ['table', 'sort', 'descending'],
      enabled: hasDocument,
      run: () => emitEditorCommand('sortTableDesc'),
    },
    {
      id: 'convertTableToHtml',
      category: 'insert',
      keywords: ['table', 'html', 'advanced'],
      enabled: hasDocument,
      run: () => emitEditorCommand('convertTableToHtml'),
    },
    {
      id: 'convertHtmlTableToMarkdown',
      category: 'insert',
      keywords: ['table', 'html', 'markdown'],
      enabled: hasDocument,
      run: () => emitEditorCommand('convertHtmlTableToMarkdown'),
    },
    {
      id: 'hr',
      category: 'insert',
      enabled: hasDocument,
      run: () => emitBlockFormat('hr'),
    },
    {
      id: 'footnote',
      category: 'insert',
      enabled: hasDocument,
      run: () => emitBlockFormat('footnote'),
    },
    {
      id: 'linkReference',
      category: 'insert',
      enabled: hasDocument,
      run: () => emitBlockFormat('linkReference'),
    },
    {
      id: 'toc',
      category: 'insert',
      enabled: hasDocument,
      run: () => emitBlockFormat('toc'),
    },
    {
      id: 'yaml',
      category: 'insert',
      enabled: hasDocument,
      run: () => emitBlockFormat('yaml'),
    },
    {
      id: 'bold',
      category: 'format',
      keywords: ['bold'],
      shortcuts: [{ code: 'KeyB', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('bold'),
    },
    {
      id: 'italic',
      category: 'format',
      keywords: ['italic'],
      shortcuts: [{ code: 'KeyI', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('italic'),
    },
    {
      id: 'underline',
      category: 'format',
      keywords: ['underline'],
      shortcuts: [{ code: 'KeyU', mod: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('underline'),
    },
    {
      id: 'strikethrough',
      category: 'format',
      keywords: ['strikethrough'],
      shortcuts: [{ code: 'Digit5', alt: true, shift: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('strikethrough'),
    },
    {
      id: 'inlineCode',
      category: 'format',
      keywords: ['code'],
      shortcuts: [{ code: 'Backquote', mod: true, shift: true }],
      enabled: hasDocument,
      run: () => emitInlineFormat('code'),
    },
    {
      id: 'paragraph',
      category: 'format',
      keywords: ['paragraph'],
      shortcuts: [{ code: 'Digit0', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('paragraph'),
    },
    ...([1, 2, 3, 4, 5, 6] as const).map((level) => ({
      id: `h${level}` as CommandId,
      category: 'format' as const,
      keywords: [`h${level}`, 'heading'],
      shortcuts: [{ code: `Digit${level}`, mod: true }],
      enabled: hasDocument,
      run: () => emitHeading(`h${level}`),
    })),
    {
      id: 'increaseHeading',
      category: 'format',
      shortcuts: [{ code: 'Equal', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('increaseHeading'),
    },
    {
      id: 'decreaseHeading',
      category: 'format',
      shortcuts: [{ code: 'Minus', mod: true }],
      enabled: hasDocument,
      run: () => emitBlockFormat('decreaseHeading'),
    },
    {
      id: 'clearFormat',
      category: 'format',
      shortcuts: [{ code: 'Backslash', mod: true }],
      enabled: hasDocument,
      run: () => emitEditorCommand('clearFormat'),
    },
    {
      id: 'moveParagraphUp',
      category: 'format',
      keywords: ['block', 'paragraph', 'move', 'up'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveParagraphUp'),
    },
    {
      id: 'moveParagraphDown',
      category: 'format',
      keywords: ['block', 'paragraph', 'move', 'down'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveParagraphDown'),
    },
    {
      id: 'duplicateParagraph',
      category: 'format',
      keywords: ['block', 'paragraph', 'duplicate', 'copy'],
      enabled: hasDocument,
      run: () => emitEditorCommand('duplicateParagraph'),
    },
    {
      id: 'deleteParagraph',
      category: 'format',
      keywords: ['block', 'paragraph', 'delete', 'remove'],
      enabled: hasDocument,
      run: () => emitEditorCommand('deleteParagraph'),
    },
    {
      id: 'moveSectionUp',
      category: 'format',
      keywords: ['block', 'section', 'heading', 'move', 'up'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveSectionUp'),
    },
    {
      id: 'moveSectionDown',
      category: 'format',
      keywords: ['block', 'section', 'heading', 'move', 'down'],
      enabled: hasDocument,
      run: () => emitEditorCommand('moveSectionDown'),
    },
    {
      id: 'duplicateSection',
      category: 'format',
      keywords: ['block', 'section', 'heading', 'duplicate', 'copy'],
      enabled: hasDocument,
      run: () => emitEditorCommand('duplicateSection'),
    },
    {
      id: 'foldCurrentHeading',
      category: 'format',
      keywords: ['block', 'section', 'heading', 'fold'],
      enabled: hasDocument,
      run: () => emitEditorCommand('foldCurrentHeading'),
    },
    {
      id: 'selectionQuote',
      category: 'format',
      keywords: ['block', 'selection', 'quote'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionQuote'),
    },
    {
      id: 'selectionCalloutNote',
      category: 'format',
      keywords: ['block', 'selection', 'callout', 'note'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutNote'),
    },
    {
      id: 'selectionCalloutWarning',
      category: 'format',
      keywords: ['block', 'selection', 'callout', 'warning'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutWarning'),
    },
    {
      id: 'selectionCalloutTip',
      category: 'format',
      keywords: ['block', 'selection', 'callout', 'tip'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionCalloutTip'),
    },
    {
      id: 'selectionUnorderedList',
      category: 'format',
      keywords: ['block', 'selection', 'list', 'unordered'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionUnorderedList'),
    },
    {
      id: 'selectionOrderedList',
      category: 'format',
      keywords: ['block', 'selection', 'list', 'ordered'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionOrderedList'),
    },
    {
      id: 'selectionTaskList',
      category: 'format',
      keywords: ['block', 'selection', 'task', 'list'],
      enabled: hasDocument,
      run: () => emitEditorCommand('selectionTaskList'),
    },
  ] satisfies CommandDefinition[];
}
