import type { CommandId } from './types';

export type CommandPaletteGroup =
  | 'file'
  | 'document'
  | 'export'
  | 'diagnostics'
  | 'links'
  | 'settings';

export const COMMAND_PALETTE_GROUP_ORDER: CommandPaletteGroup[] = [
  'file',
  'document',
  'export',
  'diagnostics',
  'links',
  'settings',
];

const paletteGroupByCommand = {
  new: 'file',
  newWindow: 'file',
  open: 'file',
  openFolder: 'file',
  quickOpen: 'file',
  save: 'file',
  saveAs: 'file',
  openCurrentLocation: 'file',
  closeDocument: 'file',

  undo: 'document',
  redo: 'document',
  cut: 'document',
  copy: 'document',
  paste: 'document',
  pastePlain: 'document',
  selectAll: 'document',
  showSearch: 'document',
  workspaceSearch: 'document',
  showReplace: 'document',
  copyPlain: 'document',
  copyMd: 'document',
  copyHtml: 'document',
  link: 'document',
  insertImage: 'document',
  insertCallout: 'document',
  insertToggle: 'document',
  codeBlock: 'document',
  mathBlock: 'document',
  quote: 'document',
  orderedList: 'document',
  unorderedList: 'document',
  taskList: 'document',
  insertTable: 'document',
  formatTable: 'document',
  addTableRow: 'document',
  addTableColumn: 'document',
  deleteTableRow: 'document',
  deleteTableColumn: 'document',
  alignTableColumnLeft: 'document',
  alignTableColumnCenter: 'document',
  alignTableColumnRight: 'document',
  insertTableRowAbove: 'document',
  insertTableRowBelow: 'document',
  insertTableColumnLeft: 'document',
  insertTableColumnRight: 'document',
  moveTableRowUp: 'document',
  moveTableRowDown: 'document',
  moveTableColumnLeft: 'document',
  moveTableColumnRight: 'document',
  selectTable: 'document',
  copyTableMarkdown: 'document',
  copyTableHtml: 'document',
  copyTableCsv: 'document',
  copyTableTsv: 'document',
  sortTableAsc: 'document',
  sortTableDesc: 'document',
  convertTableToHtml: 'document',
  convertHtmlTableToMarkdown: 'document',
  hr: 'document',
  footnote: 'document',
  linkReference: 'document',
  toc: 'document',
  yaml: 'document',
  bold: 'document',
  italic: 'document',
  underline: 'document',
  strikethrough: 'document',
  inlineCode: 'document',
  paragraph: 'document',
  h1: 'document',
  h2: 'document',
  h3: 'document',
  h4: 'document',
  h5: 'document',
  h6: 'document',
  increaseHeading: 'document',
  decreaseHeading: 'document',
  clearFormat: 'document',
  moveParagraphUp: 'document',
  moveParagraphDown: 'document',
  duplicateParagraph: 'document',
  deleteParagraph: 'document',
  moveSectionUp: 'document',
  moveSectionDown: 'document',
  duplicateSection: 'document',
  foldCurrentHeading: 'document',
  selectionQuote: 'document',
  selectionCallout: 'document',
  selectionCalloutNote: 'document',
  selectionCalloutWarning: 'document',
  selectionCalloutTip: 'document',
  selectionCalloutImportant: 'document',
  selectionUnorderedList: 'document',
  selectionOrderedList: 'document',
  selectionTaskList: 'document',
  sourceMode: 'document',
  splitMode: 'document',
  previewMode: 'document',
  toggleSidebar: 'document',
  showFiles: 'document',
  showDocs: 'document',
  showOutline: 'document',
  focusMode: 'document',
  typewriterMode: 'document',
  wordWrap: 'document',
  statusBar: 'document',
  actualSize: 'document',
  zoomIn: 'document',
  zoomOut: 'document',
  templateReadme: 'document',
  templatePrd: 'document',
  templateMeeting: 'document',
  templateWeekly: 'document',
  templateTechnicalPlan: 'document',
  templateArticle: 'document',
  templatePaperDraft: 'document',
  templateReadingNote: 'document',
  templateResearchSummary: 'document',
  templateWhitePaper: 'document',
  openDocumentProperties: 'document',

  print: 'export',
  exportHtml: 'export',
  exportPdf: 'export',
  exportDocx: 'export',
  exportPng: 'export',
  exportWithPrevious: 'export',
  exportOverwritePrevious: 'export',
  exportSettings: 'export',

  showDocumentLinks: 'links',
  showBacklinks: 'links',
  showRelationGraph: 'links',

  mdReference: 'settings',
  migrationGuide: 'settings',
  showShortcuts: 'settings',
  checkUpdate: 'settings',
  github: 'settings',
  feedback: 'settings',
  about: 'settings',
  preferences: 'settings',
  themeMiaoyan: 'settings',
  themeInkstone: 'settings',
  themeSlate: 'settings',
  themeMono: 'settings',
  themeNocturne: 'settings',
  minimize: 'settings',
  fullscreen: 'settings',
  alwaysOnTop: 'settings',
  devTools: 'settings',
} satisfies Record<CommandId, CommandPaletteGroup>;

export function getCommandPaletteGroup(commandId: CommandId): CommandPaletteGroup {
  return paletteGroupByCommand[commandId];
}
